package com.earthlocals.earthlocals.system;// Generated by Selenium IDE

import jakarta.transaction.Transactional;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.context.TestPropertySource;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.io.IOException;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@Transactional
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@TestPropertySource(locations = "classpath:application-test.properties")
@Testcontainers
public class GestioneUtenteSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @BeforeEach
    public void setUp() {
        driver = new FirefoxDriver();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC1_1RegistrazioneVolontarioConSuccesso() throws IOException {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'India']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(file.getFilePath().toAbsolutePath().toString());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("loginFormContainer")).click();
        assertEquals(
                driver.findElement(By.cssSelector(".alert")).getText(),
                "Ti abbiamo inviato una mail!\nConferma l'attivazione dell'account accedendo attraverso il link che trovi nella tua casella di posta elettronica.");
    }
}


