package com.earthlocals.earthlocals.system;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test") // Ensures application-test.yml is used
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class GestioneUtenteSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC1_1RegistrazioneVolontarioConSuccesso() throws IOException {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'India']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("loginFormContainer")).click();
        assertEquals(
                driver.findElement(By.cssSelector(".alert")).getText(),
                "Ti abbiamo inviato una mail!\nConferma l'attivazione dell'account accedendo attraverso il link che trovi nella tua casella di posta elettronica.");
    }

    @Test
    public void TC1_2Registrazionevolontarioconemailpresente() throws IOException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("andrea.squitieri@mail.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(2004, 4, 1))
                .sesso('M')
                .pending(false)
                .build();
        utenteRepository.save(utente);
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("nazionalitaRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(123)")).click();
        driver.findElement(By.id("confirmPasswordRegistrationForm")).click();
        driver.findElement(By.id("confirmPasswordRegistrationForm")).click();
        {
            WebElement element = driver.findElement(By.id("confirmPasswordRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).click();
        {
            WebElement element = driver.findElement(By.id("emailRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        driver.findElement(By.id("sessoRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".invalid-feedback"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "L'email è già registrata");
    }

    @Test
    public void TC3_1Loginsuccessfull() {
         driver.get("http://localhost:8080/");
         driver.manage().window().setSize(new Dimension(1280, 672));
         driver.findElement(By.linkText("Log in")).click();
         driver.findElement(By.id("inputEmailLoginForm")).click();
         driver.findElement(By.id("inputEmailLoginForm")).sendKeys("francesconiemiec23@gmail.com");
         driver.findElement(By.id("inputPasswordLoginForm")).click();
         driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("MiaoMeow24!");
         driver.findElement(By.cssSelector(".btn")).click();
         {
             List<WebElement> elements = driver.findElements(By.id("bannerHomePage"));
             assert(elements.size() == 0);
         }
    }

    @Test
    public void TC3_2Emailnonpresente() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert")).getText(), "E-mail o password non valida");
    }

    @Test
    public void TC3_3PasswordErrata() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("pwnnsicura");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert")).getText(), "E-mail o password non valida");
    }


}


