package com.earthlocals.earthlocals.systemtesting.gestioneutente;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.PaeseRepository;
import com.earthlocals.earthlocals.model.PasswordResetTokenRepository;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class EditPasswordSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private PasswordResetTokenRepository passwordResetTokenRepository;
    @Autowired
    private PaeseRepository paeseRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }


    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC5_1PasswordModificataConSuccesso() throws InterruptedException {
        var oldPassword = "mGdk02@L";
        var paese = paeseRepository.findById(1);
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password(passwordEncoder.encode(oldPassword))
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(paese.orElseThrow()).pending(false)
                .build();
        utenteRepository.save(utente);

        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("mario.rossi@mariorossi.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys(oldPassword);
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit-password\"]")).click();
        driver.findElement(By.id("currentPasswordEditPasswordForm")).sendKeys(oldPassword);
        driver.findElement(By.id("newPasswordEditPasswordForm")).sendKeys("Lc67Jk!d");
        driver.findElement(By.id("matchingPasswordEditPasswordForm")).sendKeys("Lc67Jk!d");
        driver.findElement(By.cssSelector("#editPasswordForm button.btn[type=submit]")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-success")).getText(), "Cambio password effettuato con successo! :]");
    }


}


