package com.earthlocals.earthlocals.systemtesting.gestioneutente;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.PasswordResetToken;
import com.earthlocals.earthlocals.model.PasswordResetTokenRepository;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class PasswordRecoveryFinalizationSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private PasswordResetTokenRepository passwordResetTokenRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }


    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC7_1RecuperoPasswordConSuccesso() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null).pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-success")).getText(), "Password cambiata con successo");
    }

    @Test
    public void TC7_2RecuperoPasswordTokenNonValido() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        passwordResetTokenRepository.delete(resetToken);
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-danger")).getText(), "Il token di reset non è valido");
    }

    @Test
    public void TC7_3RecuperoPasswordTokenScaduto() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        resetToken.setExpiryDate(LocalDateTime.of(1900, 10, 10, 0, 0));
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-danger")).getText(), "Il token di reset è scaduto");
    }

    @Test
    public void TC7_4RecuperoPasswordNoSpeciale() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk1d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Lc67Jk1d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La nuova password deve contenere almeno un carattere speciale");
    }

    @Test
    public void TC7_5RecuperoPasswordNoMinuscolo() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("LC67JK!D");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("LC67JK!D");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La nuova password deve contenere almeno un carattere minuscolo");
    }

    @Test
    public void TC7_6RecuperoPasswordNoMaiuscolo() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("lc67jk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("lc67jk!d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La nuova password deve contenere almeno un carattere maiuscolo");
    }

    @Test
    public void TC7_7RecuperoPasswordNoNumero() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("LcdTJk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("LcdTJk!d");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La nuova password deve contenere almeno un numero");
    }

    @Test
    public void TC7_8RecuperoPasswordNoLunghezza() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk!");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Lc67Jk!");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La nuova password deve essere lunga almeno 8 caratteri");
    }

    @Test
    public void TC7_9RecuperoPasswordNonCoincidono() throws InterruptedException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(false)
                .build();
        utenteRepository.save(utente);

        var resetToken = new PasswordResetToken(utente, "token");
        passwordResetTokenRepository.save(resetToken);
        driver.get(LocalTestWebServer.obtain(this.context).uri("/resetPasswordConfirm?token=" + resetToken.getToken()));
        driver.findElement(By.id("passwordReset")).sendKeys("Lc67Jk!d");
        driver.findElement(By.id("matchingPasswordReset")).sendKeys("Password1!");
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Le password non coincidono");
    }


}


