package com.earthlocals.earthlocals.systemtesting.gestioneutente;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import com.earthlocals.earthlocals.model.VerificationToken;
import com.earthlocals.earthlocals.model.VerificationTokenRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class RegistrationConfirmationSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private VerificationTokenRepository verificationTokenRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC2_1ConfermaRegistrazioneConSuccesso() throws IOException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(true)
                .build();
        utenteRepository.save(utente);

        var verificationToken = new VerificationToken(utente, "token");
        verificationTokenRepository.save(verificationToken);

        driver.get(LocalTestWebServer.obtain(this.context).uri("/registration/registrationConfirm?token=" + verificationToken.getToken()));
        driver.manage().window().setSize(new Dimension(1280, 672));
        assertEquals(driver.findElement(By.cssSelector(".alert")).getText(), "Il tuo account è stato verificato con successo");
    }

    @Test
    public void TC2_2ConfermaRegistrazioneTokenNonPresente() throws IOException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(true)
                .build();
        utenteRepository.save(utente);

        driver.get(LocalTestWebServer.obtain(this.context).uri("/registration/registrationConfirm?token=" + UUID.randomUUID()));
        driver.manage().window().setSize(new Dimension(1280, 672));
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-danger")).getText(), "Il token di verifica non è valido");
    }

    @Test
    public void TC2_3ConfermaRegistrazioneTokenScaduto() throws IOException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("mario.rossi@mariorossi.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(1999, 12, 25))
                .sesso('M')
                .nazionalita(null)
                .pending(true)
                .build();
        utenteRepository.save(utente);
        var verificationToken = new VerificationToken(utente, "token");
        verificationToken.setExpiryDate(LocalDateTime.of(1900, 10, 10, 0, 0));
        verificationTokenRepository.save(verificationToken);


        driver.get(LocalTestWebServer.obtain(this.context).uri("/registration/registrationConfirm?token=" + verificationToken.getToken()));

        driver.manage().window().setSize(new Dimension(1280, 672));
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-danger")).getText(), "Il token di verifica non è valido");
    }
}


