package com.earthlocals.earthlocals.systemtesting.gestionemissione;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.Missione;
import com.earthlocals.earthlocals.model.MissioneRepository;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class AcceptMissioniTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private MissioneRepository missioneRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");

        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    private void forceLogin() {
        driver.manage().deleteAllCookies();
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("organizer1@gmail.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    @Test
    public void TC10_1AcceptMissioneSuccess() throws Exception {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("moderator@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("test");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();

        driver.findElement(By.cssSelector("tr:nth-child(2) .fa-check")).click();
        driver.findElement(By.cssSelector("div[aria-modal=true] form > .btn")).click();
        driver.findElement(By.cssSelector(".table")).click();

        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
        assertEquals(driver.findElement(By.linkText("Programma di volontariato per la pianificazione agricola e la mappatura delle risorse in permacultura")).getText(), "Programma di volontariato per la pianificazione agricola e la mappatura delle risorse in permacultura");
    }

    @Test
    public void TC10_2AcceptMissioneNotLoggedAnymore() throws Exception {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("moderator@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("test");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();

        driver.manage().deleteAllCookies();

        driver.findElement(By.linkText("Gestione missioni")).click();
        driver.findElement(By.cssSelector(".text-center")).click();
        assertEquals(driver.findElement(By.cssSelector(".text-center")).getText(), "Log in");
    }

    @Test
    public void TC10_3AcceptMissioneNotModerator() throws Exception {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("organizer1@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();

        driver.get(LocalTestWebServer.obtain(this.context).uri("/account/moderator/missions"));

        driver.findElement(By.cssSelector(".col-md-12")).click();
        driver.findElement(By.cssSelector(".col-md-12")).click();
        driver.findElement(By.cssSelector(".col-md-12")).click();
        assertEquals(driver.findElement(By.cssSelector("h2")).getText(), "403 - Accesso negato!");
    }

    @Test
    public void TC10_4AcceptMissioneAlreadyAccepted() throws Exception {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("moderator@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("test");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        WebElement checkBtn = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.cssSelector("tr:nth-child(3) .fa-check")
                )
        );
        checkBtn.click();

        long missioneId = 402;
        Missione missione = missioneRepository.findById(missioneId).orElseThrow();
        missioneRepository.delete(missione);

        WebElement confermaBtn = wait.until(
                ExpectedConditions.elementToBeClickable(
                        By.cssSelector("div[aria-modal=true] form > .btn")
                )
        );
        confermaBtn.click();

        WebElement errorMsg = wait.until(
                ExpectedConditions.visibilityOfElementLocated(
                        By.cssSelector(".col-md-12 > p")
                )
        );
        assertEquals(
                "Ci dispiace, si è verificato un errore. Attendi e riprova.",
                errorMsg.getText()
        );
    }


}