package com.earthlocals.earthlocals.systemtesting.gestionemissione;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class AcceptMissioniTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private MissioneRepository missioneRepository;
    @Autowired
    private CandidaturaRepository candidaturaRepository;
    @Autowired
    private PaeseRepository paeseRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");

        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void TC10_1AcceptMissioneSuccess() throws Exception{
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("moderator@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("test");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();

        driver.findElement(By.cssSelector("tr:nth-child(2) .fa-check")).click();
        driver.findElement(By.cssSelector("div[aria-modal=true] form > .btn")).click();
        driver.findElement(By.cssSelector(".table")).click();

        driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
        assertEquals(driver.findElement(By.linkText("Programma di volontariato per la pianificazione agricola e la mappatura delle risorse in permacultura")).getText(), "Programma di volontariato per la pianificazione agricola e la mappatura delle risorse in permacultura");

    }
}