package com.earthlocals.earthlocals.systemtesting.gestionemissione;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.*;
import org.assertj.core.api.WithAssertions;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class FilteredMissionsSearchSystemTest implements WithAssertions {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;
    @Autowired
    private MissioneRepository missioneRepository;
    @Autowired
    private CandidaturaRepository candidaturaRepository;
    @Autowired
    private PaeseRepository paeseRepository;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC11_1FiltroMissioniUnaPresente() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        WebElement dropdown = driver.findElement(By.name("paeseId"));
        dropdown.findElement(By.xpath("//option[. = 'Taiwan']")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        List<WebElement> elements = driver.findElements(By.cssSelector(".card-img"));
        assertEquals(1, elements.size());
    }

    @Test
    public void TC11_2FiltroMissioniDuePresenti() throws InterruptedException {
        var afghanistan = paeseRepository.findById(5).orElseThrow();
        var creatore = utenteRepository.findById(203L).orElseThrow();
        var missione1 = Missione.missioneBuilder()
                .nome("Missione1")
                .paese(afghanistan)
                .citta("Kabul")
                .descrizione("Descrizione test 1")
                .dataInizio(LocalDate.of(2026, 10, 10))
                .dataFine(LocalDate.of(2026, 10, 15))
                .competenzeRichieste("Competenze test 1")
                .requisitiExtra("Requisiti extra 1")
                .immagine("test1.jpg")
                .creatore(creatore)
                .build();
        missione1.accettaMissione();
        var missione2 = Missione.missioneBuilder()
                .nome("Missione2")
                .paese(afghanistan)
                .citta("Kabul")
                .descrizione("Descrizione test 2")
                .dataInizio(LocalDate.of(2026, 10, 10))
                .dataFine(LocalDate.of(2026, 10, 15))
                .competenzeRichieste("Competenze test 2")
                .requisitiExtra("Requisiti extra 2")
                .immagine("test2.jpg")
                .creatore(creatore)
                .build();
        missione2.accettaMissione();

        missioneRepository.saveAll(List.of(missione1, missione2));
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();

        WebElement dropdown = driver.findElement(By.name("paeseId"));
        dropdown.findElement(By.xpath("//option[. = 'Afghanistan']")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        List<WebElement> elements = driver.findElements(By.cssSelector(".card"));
        assertEquals(elements.size(), 2);
    }

    @Test
    public void TC11_3FiltroMissioniNessuna() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        driver.findElement(By.name("paeseId")).click();
        {
            WebElement dropdown = driver.findElement(By.name("paeseId"));
            dropdown.findElement(By.xpath("//option[. = 'Morocco']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(158)")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.cssSelector(".container-fluid")).click();
        {
            assertEquals(driver.findElement(By.cssSelector(".w-50")).getText(), "Trovate 0 missioni");
        }
    }

    @Test
    public void TC11_4FiltroNotSelected() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(3) .card-title"));
            assertFalse(elements.isEmpty());
        }
    }
}