package com.earthlocals.earthlocals.systemtesting.gestionemissione;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class ViewOrganizedMissioneSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    private void forceLogin() {
        driver.manage().deleteAllCookies();
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("francesconiemiec23@gmail.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("MiaoMeow24!");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    @Test
    public void TC11_1MissioniOrganizzateOne() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("mario.rossi@example.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("MiaoMeow24!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(3) .card-img"));
            assert (elements.size() == 1);
        }
    }

    @Test
    public void TC11_2MissioniNotLoggedAnymore() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("organizer2@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();

        driver.manage().deleteAllCookies();

        driver.findElement(By.linkText("Gestione missioni")).click();
        driver.findElement(By.cssSelector(".text-center")).click();
        assertEquals(driver.findElement(By.cssSelector(".text-center")).getText(), "Log in");
    }

    @Test
    public void TC11_3MissioniNotAuthorized() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("francesconiemiec23@gmail.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("MiaoMeow24!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.get(LocalTestWebServer.obtain(this.context).uri("/account/organizer/missions"));
        String pageSource = driver.getPageSource();

        assert (
                pageSource.contains("403") ||
                        pageSource.contains("Accesso negato") ||
                        driver.getCurrentUrl().contains("login")
        );
    }

    @Test
    public void TC11_4MissioniMoreThanOne() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("organizer3@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();
        driver.findElement(By.cssSelector(".row-cols-md-2")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(2) .card-text"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void TC11_5MissioniNonPresenti() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("organizer1@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).click();
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Profilo")).click();
        driver.findElement(By.linkText("Gestione missioni")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(3) .card-img"));
            assert (elements.size() == 0);
        }
    }
}


