package com.earthlocals.earthlocals.systemtesting;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class EditProfileInformationSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC4_1ModificaProfiloConSuccesso() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("volunteer@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();
        driver.findElement(By.id("firstNameEditForm")).clear();
        driver.findElement(By.id("firstNameEditForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameEditForm")).clear();
        driver.findElement(By.id("lastNameEditForm")).sendKeys("Squiteri");
        driver.findElement(By.id("nazionalitaEditForm")).sendKeys("1");
        driver.findElement(By.id("dataNascitaEditForm")).clear();
        driver.findElement(By.id("dataNascitaEditForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("sessoEditForm")).sendKeys("M");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertEquals(driver.findElement(By.cssSelector(".alert.alert-success")).getText(), "Modifica profilo effettuata con successo");
    }

    @Test
    public void TC4_2ModificaProfiloNonAutenticato() throws InterruptedException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("volunteer@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();

        driver.manage().deleteAllCookies();

        driver.findElement(By.id("firstNameEditForm")).clear();
        driver.findElement(By.id("firstNameEditForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameEditForm")).clear();
        driver.findElement(By.id("lastNameEditForm")).sendKeys("Squiteri");
        driver.findElement(By.id("nazionalitaEditForm")).sendKeys("1");
        driver.findElement(By.id("dataNascitaEditForm")).clear();
        driver.findElement(By.id("dataNascitaEditForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("sessoEditForm")).sendKeys("M");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertEquals("403 - Accesso negato!", driver.findElement(By.cssSelector("h2")).getText());
    }

    @Test
    public void TC4_3ModificaProfiloFormatoNomeNonRispettato() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("volunteer@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();
        driver.findElement(By.id("firstNameEditForm")).clear();
        driver.findElement(By.id("firstNameEditForm")).sendKeys(" ");
        driver.findElement(By.id("lastNameEditForm")).clear();
        driver.findElement(By.id("lastNameEditForm")).sendKeys("Squiteri");
        driver.findElement(By.id("nazionalitaEditForm")).sendKeys("1");
        driver.findElement(By.id("dataNascitaEditForm")).clear();
        driver.findElement(By.id("dataNascitaEditForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("sessoEditForm")).sendKeys("M");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il nome è obbligatorio");
    }

    @Test
    public void TC4_4ModificaProfiloFormatoCognomeNonRispettato() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("volunteer@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();
        driver.findElement(By.id("firstNameEditForm")).clear();
        driver.findElement(By.id("firstNameEditForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameEditForm")).clear();
        driver.findElement(By.id("lastNameEditForm")).sendKeys(" ");
        driver.findElement(By.id("nazionalitaEditForm")).sendKeys("1");
        driver.findElement(By.id("dataNascitaEditForm")).clear();
        driver.findElement(By.id("dataNascitaEditForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("sessoEditForm")).sendKeys("M");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il cognome è obbligatorio");
    }

    @Test
    public void TC4_5ModificaProfiloFormatoDataDiNascitaNonRispettato() {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Log in")).click();
        driver.findElement(By.id("inputEmailLoginForm")).sendKeys("volunteer@earthlocals.com");
        driver.findElement(By.id("inputPasswordLoginForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector("a[href=\"/account/edit\"]")).click();
        driver.findElement(By.id("firstNameEditForm")).clear();
        driver.findElement(By.id("firstNameEditForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameEditForm")).clear();
        driver.findElement(By.id("lastNameEditForm")).sendKeys("Squitieri");
        driver.findElement(By.id("nazionalitaEditForm")).sendKeys("1");
        driver.findElement(By.id("dataNascitaEditForm")).clear();
        driver.findElement(By.id("dataNascitaEditForm")).sendKeys("2030-04-01");
        driver.findElement(By.id("sessoEditForm")).sendKeys("M");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La data di nascita inserita non è valida");
    }

}


