package com.earthlocals.earthlocals.systemtesting;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class FiltroMissioniTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @Autowired
    private ApplicationContext context;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;
    @Autowired
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC12_2FiltroMissioniUnaPresente(){
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        {
            WebElement dropdown = driver.findElement(By.name("paeseId"));
            dropdown.findElement(By.xpath("//option[. = 'Taiwan']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(44)")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".card-img"));
            assert(elements.size() > 0);
        }
    }

    @Test
    public void TC12_1FiltroMissioniDuePresenti() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        driver.findElement(By.name("paeseId")).click();
        {
            WebElement dropdown = driver.findElement(By.name("paeseId"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(124)")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.cssSelector(".row-cols-md-2")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(2) .card-img"));
            assert(elements.size() > 0);
        }
    }
    @Test
    public void TC12_3FiltroMissioniNessuna() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        driver.findElement(By.name("paeseId")).click();
        {
            WebElement dropdown = driver.findElement(By.name("paeseId"));
            dropdown.findElement(By.xpath("//option[. = 'Morocco']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(158)")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.cssSelector(".container-fluid")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("span:nth-child(3)"));
            assert(elements.size() > 0);
        }
    }

    @Test
    public void TC12_5FiltroNotSelected() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1280, 672));
        driver.findElement(By.linkText("Opportunità")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".col:nth-child(3) .card-title"));
            assert(elements.size() > 0);
        }
    }
}