package com.earthlocals.earthlocals.systemtesting;// Generated by Selenium IDE

import com.earthlocals.earthlocals.config.SystemTestAppConfig;
import com.earthlocals.earthlocals.config.TestcontainerConfig;
import com.earthlocals.earthlocals.model.Utente;
import com.earthlocals.earthlocals.model.UtenteRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.http.server.LocalTestWebServer;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.web.context.WebApplicationContext;

import java.io.IOException;
import java.time.Duration;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ActiveProfiles("test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import({SystemTestAppConfig.class, TestcontainerConfig.class})
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class VolunteerRegistrationSystemTest {
    private final ClassPathResource file = new ClassPathResource("static/resources/files/sample.pdf");
    JavascriptExecutor js;
    @LocalServerPort
    private int port;
    private WebDriver driver;
    private Map<String, Object> vars;
    @Autowired
    private UtenteRepository utenteRepository;

    @Autowired
    private ApplicationContext context;

    @BeforeEach
    public void setUp(WebApplicationContext context) {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("-headless");
        driver = new FirefoxDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    private String getFilePath() throws IOException {
        return file.getFilePath().toAbsolutePath().toString();

    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void TC1_1RegistrazioneVolontarioConSuccesso() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'India']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("loginFormContainer")).click();
        assertEquals(
                driver.findElement(By.cssSelector(".alert")).getText(),
                "Ti abbiamo inviato una mail!\nConferma l'attivazione dell'account accedendo attraverso il link che trovi nella tua casella di posta elettronica.");
    }

    @Test
    public void TC1_2Registrazionevolontarioconemailpresente() throws IOException {
        var utente = Utente.utenteBuilder()
                .nome("Mario")
                .cognome("Rossi")
                .email("andrea.squitieri@mail.com")
                .password("PasswordMoltoSicura1234!")
                .dataNascita(LocalDate.of(2004, 4, 1))
                .sesso('M')
                .pending(false)
                .build();
        utenteRepository.save(utente);
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("nazionalitaRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(123)")).click();
        driver.findElement(By.id("confirmPasswordRegistrationForm")).click();
        driver.findElement(By.id("confirmPasswordRegistrationForm")).click();
        {
            WebElement element = driver.findElement(By.id("confirmPasswordRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).click();
        {
            WebElement element = driver.findElement(By.id("emailRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        driver.findElement(By.id("sessoRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".invalid-feedback"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "L'email è già registrata");
    }

    @Test
    public void TC1_3RegistrazioneVolontarioFormatoNomeErrato() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys(" ");
        driver.findElement(By.id("lastNameRegistrationForm")).click();
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(123)")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il nome è obbligatorio");
    }

    @Test
    public void TC1_4RegistrazioneFormatoCognomeErrato() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1908, 1023));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys(" ");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'India']")).click();
        }
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il cognome è obbligatorio");
    }


    @Test
    public void TC1_5RegistrazioneVolontarioFormatoDataNascitaErrato() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).click();
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).click();
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.cssSelector("div:nth-child(6)")).click();
        driver.findElement(By.id("passwordRegistrationForm")).click();
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).click();
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement element = driver.findElement(By.id("nazionalitaRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.id("nazionalitaRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.id("nazionalitaRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.id("nazionalitaRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Iran']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(97)")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).click();
        {
            WebElement element = driver.findElement(By.id("dataNascitaRegistrationForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2030-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).click();
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        driver.findElement(By.id("sessoRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".invalid-feedback")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La data di nascita inserita non è valida");
    }

    @Test
    public void TC1_6RegistrazioneVolontarioDataScadenzaPassaportoNonValida() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("nazionalitaRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(123)")).click();
        driver.findElement(By.cssSelector("#registrationForm > div:nth-child(4)")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).click();
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).click();
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).click();
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        driver.findElement(By.id("sessoRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("registrationForm")).click();
        assertEquals(driver.findElement(By.cssSelector("div:nth-child(11) > .invalid-feedback")).getText(), "La data di scadenza del passaporto inserita non è valida");
    }

    @Test
    public void TC1_7RegistrazioneVolontarioDataEmissionePassaportoNonValida() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2080-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        driver.findElement(By.id("sessoRegistrationForm")).click();
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector("#sessoRegistrationForm > option:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "La data di emissione del passaporto inserita non è valida");
    }

    @Test
    public void TC1_8RegistrazioneVolontarioEmailNonValidaUsernameMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector("div:nth-child(4) > .invalid-feedback")).getText(), "L'email inserita non è valida");
    }

    @Test
    public void TC1_9RegistrazioneVolontarioEmailNonValidaChiocciolaMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitiermail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector("div:nth-child(4) > .invalid-feedback")).getText(), "L'email inserita non è valida");
    }

    @Test
    public void TC1_10RegistrazioneVolontarioEmailNonValidaDominioMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector("div:nth-child(4) > .invalid-feedback")).getText(), "L'email inserita non è valida");
    }

    @Test
    public void TC1_11RegistrazioneVolontarioPasswordCarattereSpecialeMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("Pwnnsicur4");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("Pwnnsicur4");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback:nth-child(3)")).getText(), "La password deve contenere almeno un carattere speciale");
    }

    @Test
    public void TC1_12RegistrazioneVolontarioPasswordCarattereMinuscoloMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PWNNS!CUR4");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PWNNS!CUR4");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback:nth-child(3)")).getText(), "La password deve contenere almeno un carattere minuscolo");
    }


    @Test
    public void TC1_13RegistrazioneVolontarioPasswordCarattereMaiuscoloMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("pwnns!cur4");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("pwnns!cur4");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback:nth-child(3)")).getText(), "La password deve contenere almeno un carattere maiuscolo");
    }


    @Test
    public void TC1_14RegistrazioneVolontarioPasswordNumeroMancante() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("Pwnns!cura");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("Pwnns!cura");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback:nth-child(3)")).getText(), "La password deve contenere almeno un numero");
    }

    @Test
    public void TC1_15RegistrazioneVolontarioPasswordTroppoCorta() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("aB3!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("aB3!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback:nth-child(3)")).getText(), "La password deve essere lunga almeno 8 caratteri");
    }

    @Test
    public void TC1_16RegistrazioneVolontarioNumeroPassaportoTroppoLungo() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASSAPORTO");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il numero del passaporto deve contenere al massimo 9 caratteri");
    }

    @Test
    public void TC1_17RegistrazioneVolontarioNumeroPassaportoCarattereSpecialeNonValido() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("ASPASS!");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il numero del passaporto deve contenere solo caratteri alfanumerici maiuscoli");
    }

    @Test
    public void TC1_18RegistrazioneVolontarioNumeroPassaportoCarattereMinuscoloNonValido() throws IOException {
        driver.get(LocalTestWebServer.obtain(this.context).uri());
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.linkText("Iscriviti")).click();
        driver.findElement(By.id("firstNameRegistrationForm")).sendKeys("Andrea");
        driver.findElement(By.id("lastNameRegistrationForm")).sendKeys("Squitieri");
        driver.findElement(By.id("emailRegistrationForm")).sendKeys("andrea.squitieri@mail.com");
        driver.findElement(By.id("passwordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        driver.findElement(By.id("confirmPasswordRegistrationForm")).sendKeys("PasswordMoltoSicura1234!");
        {
            WebElement dropdown = driver.findElement(By.id("nazionalitaRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Italia']")).click();
        }
        driver.findElement(By.id("dataNascitaRegistrationForm")).sendKeys("2004-04-01");
        driver.findElement(By.id("numeroPassaportoRegistrationForm")).sendKeys("AsPASS");
        driver.findElement(By.id("dataScadenzaPassaportoRegistrationForm")).sendKeys("2099-04-01");
        driver.findElement(By.id("dataEmissionePassaportoRegistrationForm")).sendKeys("2010-04-01");
        driver.findElement(By.id("passaportoRegistrationForm")).sendKeys(getFilePath());
        {
            WebElement dropdown = driver.findElement(By.id("sessoRegistrationForm"));
            dropdown.findElement(By.xpath("//option[. = 'Maschio']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        assertEquals(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), "Il numero del passaporto deve contenere solo caratteri alfanumerici maiuscoli");
    }

}


